version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  php:
    build: ./.docker/php
    depends_on:
      - kafka
    links: 
      - kafka
    volumes:
      - ./app/consumer-php:/usr/share/nginx/www
    working_dir: /usr/share/nginx/www

  nginx:
    build: ./.docker/nginx
    depends_on:
      - kafka
    ports:
      - '8030:80'
    depends_on:
      - php
    volumes:
      - ./app/consumer-php:/opt/work
  
  python:
    build: ./.docker/python
    depends_on:
      - kafka
    links: 
      - kafka
    volumes:
      - ./app/producer-py:/usr/src/app

  node:
    build: ./app/consumer-js
    depends_on:
      - kafka
    links: 
      - kafka
    command: echo "done"
    volumes:
      - ./app/consumer-js:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"